__title__ = 'datapress_client'
__description__ = 'DataPress API client'
__version__ = '0.0.1'
__author__ = 'DataPress Ltd.'
__author_email__ = 'admin@datapress.com'
__license__ = 'Apache 2.0'
__url__ = 'https://github.com/datapressio/dp-client'
